---
title: "Freeze-Thaw"
author: "Alicia Halhed"
date: "13/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(lubridate)
library(tidyverse)
theme_set(theme_bw())
```

## Read in the data

```{r samples}
# jay sampling dates
dates <- read_excel("~/OneDrive - University of Guelph/Alicia's Thesis/Grey Jays/metadata/jay-ft.xlsx") %>%
  # modify the dates to match weather dates
  mutate(CollectionDate = dmy(.$CollectionDate))

```

```{r weather}
setwd("~/OneDrive - University of Guelph/Alicia's Thesis/Grey Jays/weather-data")
weather <- read_csv("2020.csv") %>% 
  rbind(read_csv("2019.csv")) %>% 
  rbind(read_csv("2018.csv")) %>% 
  rbind(read_csv("2017.csv")) %>% 
  rbind(read_csv("2016.csv"))
```

```{r}
# add new freeze-thaw column
weather$FreezeThaw <- ifelse(weather$`Max Temp (°C)` > -1.9 & weather$`Min Temp (°C)` < -1.9, "Freeze-Thaw",
       ifelse(weather$`Max Temp (°C)` > -1.9 & weather$`Min Temp (°C)` > -1.9, "Warm", "Frozen"))
# add new season type column
weather$SeasonType <- ifelse(as.numeric(weather$Month) > 9, "Caching",
                            ifelse(as.numeric(weather$Month) < 4, "Pre-breeding",
                                   ifelse(as.numeric(weather$Month) < 6, "Breeding",
                                          "Summer")))
```

## Freeze thaw plot

```{r}
cacheGroup <- function(Data, Group, Date1, Date2) {
  df <- Data %>% mutate(Group = Group) %>% # labelling groups
  subset(`Date/Time` > Date1 & `Date/Time` < Date2) %>%
  # assign a number to each date in order
  .[order(.$`Date/Time`), ] %>% mutate(Number = rep(1:(0.5*nrow(. )), each=2))
  return(df)
}
```

```{r}
# fomatting columns
# caching period = October-December
# pre-breeding period = January-February
longWeather <-  weather %>%
  select(`Min Temp (°C)`, `Max Temp (°C)`,`Date/Time`, FreezeThaw, SeasonType) %>%
  rename('Daily Minimum' = `Min Temp (°C)`, 
         'Daily Maximum' = `Max Temp (°C)`) %>%
  # long formatting (for making plot)
  pivot_longer(-c(`Date/Time`, FreezeThaw, SeasonType), names_to = "Type", values_to = "Temperature")
# select only caching period and pre-breeding period by annual season
# 2016-2017
weather1 <- cacheGroup(longWeather, "2016-2017", "2016-09-01", "2017-08-31")
# 2017-2018
weather2 <- cacheGroup(longWeather, "2017-2018", "2017-09-01", "2018-08-31")
# 2018-2019
weather3 <- cacheGroup(longWeather, "2018-2019", "2018-09-01", "2019-08-31")
# 2019-2020
weather4 <- cacheGroup(longWeather, "2019-2020", "2019-09-01", "2020-08-31")
# 2020 Caching
weather5 <-cacheGroup(longWeather, "Fall 2020", "2020-09-01", "2021-01-01")
# combine groups
plotWeather <- rbind(weather1, weather2) %>% rbind(., weather3) %>% rbind(., weather4) %>% rbind(., weather5)
# clean up
rm(longWeather, weather1, weather2, weather3, weather4, weather5)
```

```{r}
# need to adjust labels for full year
ggplot(plotWeather, aes(x=Number,y=Temperature, group=Type)) + # could add in colour = FreezeThaw
  geom_line() + facet_grid(Group~.) +
  scale_x_continuous(breaks=c(1, 32, 62, 93, 124),
                     labels = c("October", "November", "December", "January", "February")) +
  geom_hline(yintercept = -1.9, linetype = "dashed") +
  theme(axis.text.x = element_text(hjust = 0, vjust = 0.5)) +
  labs(x = "Month", y = "Daily Temperature Range (°C)")
```

## How many freeze thaw events occured in the caching seasons?
```{r}
# counts of freeze thaws
plotWeather %>%
  select(Group, FreezeThaw, SeasonType) %>% 
  group_by(Group, SeasonType) %>% 
  count(vars = FreezeThaw)
# plot of counts
ggplot(na.omit(plotWeather), aes(x = Group, fill = FreezeThaw)) +
  geom_bar(position = "dodge") + scale_fill_viridis_d() +
  facet_grid(SeasonType~.) + # need to figure out reordering these
  labs(y = "Daily Temperature Events", x = "Annual Group", 
       fill = "Temperature Event")
```

## How many freeze thaw events occured in the 14 days leading up to fall sampling dates?

```{r}
#add groups to dates
metaWeather <- plotWeather %>%
  rename("CollectionDate" = "Date/Time") %>%
  select(CollectionDate, SeasonType, Group) %>% 
  unique %>% right_join(dates)
# read in aitchison DM
dmAitchison <- qiime2R::read_qza("~/OneDrive - University of Guelph/Alicia's Thesis/GreyJayMicrobiome/aitchison-distance.qza")$data %>%
  as.matrix %>% .[rownames(metaWeather), rownames(metaWeather)]
```

```{r}
eventCount <- function(column, station, event){
  # station is the data from the weather station with freeze thaw & season information
  # column is the data frame column containing the sampling dates of interest
  # event is the weather event (freeze-thaw, warm, frozen)
  df1 <- station %>% filter(`Date/Time` %in% seq(column - days(14), column - days(1), by="day"))
  df2 <- df1 %>% select(FreezeThaw) %>% count(vars = FreezeThaw)
  df3 <- df2 %>% filter(vars == event) %>% .$n
  return(df3)
}

eventCount(metaWeather$CollectionDate[4], weather, 'Freeze-Thaw')
```

```{r}
# count the number of freeze-thaw days in the 14 days prior to collection
metaWeather$FreezeThaw <- mapply(eventCount, metaWeather$CollectionDate, 
                                 station = weather, event = 'Freeze-Thaw')
# count the number of warm days in the 14 days prior to collection
metaWeather$Warm <- sapply(metaWeather$CollectionDate, eventCount, 
                                 station = weather, event = 'Warm')
metaWeather$Warm[metaWeather$Warm== "integer(0)"] <- 0
# count the number of cold days in the 14 days prior to collection
metaWeather$Frozen <- sapply(metaWeather$CollectionDate, eventCount, 
                                 station = weather, event = 'Frozen')
metaWeather$Frozen[metaWeather$Frozen== "integer(0)"] <- 0
```

## Stats
```{r}
# need to put in counts above to include here
# PERMANOVA
vegan::adonis2(dmAitchison ~ FreezeThaw + Behaviour + Group,
        data = metaWeather, na.action = na.exclude)
```




